// ------------------------------------------------------
// generated by builder.sce: Please do not edit this file
// cleaner.sce
// ------------------------------------------------------
curdir = pwd();
cleaner_path = get_file_path('cleaner.sce');
chdir(cleaner_path);
// ------------------------------------------------------
if fileinfo('loader.sce') <> [] then
  mdelete('loader.sce');
end
// ------------------------------------------------------
if fileinfo('libscigetfem_c.c') <> [] then
  mdelete('libscigetfem_c.c');
end
// ------------------------------------------------------
chdir(curdir);
// ------------------------------------------------------
