function a=loadobj(a)
% gfInteg/loadobj
% this function is automatically called by matlab when objects of class
% gfIntegare loaded from a MAT-file
  a=gfInteg('from string',b.txt);
% autogenerated mfile;
