function a=loadobj(a)
% gfMeshFem/loadobj
% this function is automatically called by matlab when objects of class
% gfMeshFemare loaded from a MAT-file
  a=gfMeshFem('from string',b.txt);
% autogenerated mfile;
