function a=loadobj(a)
% gfSpmat/loadobj
% this function is automatically called by matlab when objects of class
% gfSpmatare loaded from a MAT-file
  a=gfSpmat('from string',b.txt);
% autogenerated mfile;
