function varargout=set(obj,varargin)
% gfModel/set.m
% see gf_model_set for more help.
if (nargout),
 [varargout{1:nargout}]=gf_model_set(obj, varargin{:});
else
 gf_model_set(obj,varargin{:});
 if (exist('ans','var') == 1), varargout{1}=ans;
end;
end
% autogenerated by gen_mfiles
