function a=loadobj(a)
% gfEltm/loadobj
% this function is automatically called by matlab when objects of class
% gfEltmare loaded from a MAT-file
  a=gfEltm('from string',b.txt);
% autogenerated mfile;
