function display(mf)
% displays a mesh object
  disp(sprintf(['gfMeshFem object: ID=%u [%d bytes], qdim=%d, nbdof=%d,\n'...
		'  linked gfMesh object: dim=%d, nbpts=%d, nbcvs=%d'],double(mf.id),...
	       gf_mesh_fem_get(mf,'memsize'), gf_mesh_fem_get(mf,'qdim'), ...
	       gf_mesh_fem_get(mf,'nbdof'), gf_mesh_get(mf,'dim'), ...
	       gf_mesh_get(mf,'nbpts'), gf_mesh_get(mf,'nbcvs')));
