function a=loadobj(a)
% gfMesh/loadobj
% this function is automatically called by matlab when objects of class
% gfMeshare loaded from a MAT-file
  a=gfMesh('from string',b.txt);
% autogenerated mfile;
