function varargout=get(obj,varargin)
% gfLevelSet/get.m
% see gf_levelset_get for more help.
if (nargout),
 [varargout{1:nargout}]=gf_levelset_get(obj, varargin{:});
else
 gf_levelset_get(obj,varargin{:});
 if (exist('ans','var') == 1), varargout{1}=ans;
end;
end
% autogenerated by gen_mfiles