function varargout=set(obj,varargin)
% gfLevelSet/set.m
% see gf_levelset_set for more help.
if (nargout),
 [varargout{1:nargout}]=gf_levelset_set(obj, varargin{:});
else
 gf_levelset_set(obj,varargin{:});
 if (exist('ans','var') == 1), varargout{1}=ans;
end;
end
% autogenerated by gen_mfiles