function a=loadobj(a)
% gfSlice/loadobj
% this function is automatically called by matlab when objects of class
% gfSliceare loaded from a MAT-file
  a=gfSlice('from string',b.txt);
% autogenerated mfile;
