function display(cs)
% gfCvStruct/display displays a short summary for a gfCvStruct object
  for i=1:numel(cs),
    disp(sprintf(['gfCvStruct (convex structure) object ID=%u ' ...
		  ', dim=%d, nbpts=%d'],...
		 double(cs(i).id),...
		 gf_cvstruct_get(cs(i),'dim'),...
		 gf_cvstruct_get(cs(i),'nbpts')));
  end;
  