function varargout=get(obj, varargin)
% gfGeoTrans/get.m
% see gf_geotrans_get for more help.
if (nargout), 
  [varargout{1:nargout}] = gf_geotrans_get(obj, varargin{:});
else
  gf_geotrans_get(obj,varargin{:});
  if (exist('ans','var') == 1), varargout{1}=ans;
  end;
end;
% autogenerated mfile;
