function a=loadobj(a)
% gfGeoTrans/loadobj
% this function is automatically called by matlab when objects of class
% gfGeoTransare loaded from a MAT-file
  a=gfGeoTrans('from string',b.txt);
% autogenerated mfile;
