function display(sl)
% displays a slice object
  m=gf_slice_get(sl,'linked mesh');
  disp(sprintf(['gfSlice object: ID=%u [%d bytes], dim=%d nbpts=%d,\n'...
		'  linked gfMesh object: dim=%d, nbpts=%d, nbcvs=%d'],double(sl.id),...
	       gf_slice_get(sl,'memsize'), gf_slice_get(sl,'dim'), ...
	       gf_slice_get(sl,'nbpts'), gf_mesh_get(m,'dim'), ...
	       gf_mesh_get(m,'nbpts'), gf_mesh_get(m,'nbcvs')));
