function a=loadobj(a)
% gfPrecond/loadobj
% this function is automatically called by matlab when objects of class
% gfPrecondare loaded from a MAT-file
  a=gfPrecond('from string',b.txt);
% autogenerated mfile;
