function a=loadobj(a)
% gfMeshIm/loadobj
% this function is automatically called by matlab when objects of class
% gfMeshImare loaded from a MAT-file
  a=gfMeshIm('from string',b.txt);
% autogenerated mfile;
