#!/usr/bin/perl

`rm -f doc.tex`;
`cat entete.tex macro.tex > doc.tex`;

open F, ">>doc.tex" or die;
print F '\begin{document}', "\n\n";
print F '$\;$\\\\[3cm]\thispagestyle{empty}', "\n\n";
print F '{\begin{center} \Large Basic documentation of \\\\[2cm]', "\n\n";
print F '\Huge \bf GETFEM++ \end{center}} \newpage', "\n\n";
print F '\\noindent Copyright (C) 2001.\\\\ \\\\',  "\n";       
print F 'This is a part of GETFEM++.\\\\ \\\\',  "\n";
print F 'This program is free software; you can redistribute it and/or ';
print F 'modify it under the terms of the GNU General Public License as  ';
print F 'published by the Free Software Foundation; version 2 of ';
print F 'the License.\\\\ \\\\',  "\n";            
print F 'This program is distributed in the hope that it will be useful, ';
print F 'but WITHOUT ANY WARRANTY; without even the implied warranty of ';
print F 'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the ';
print F 'GNU General Public License for more details.\\\\ \\\\',  "\n";                                                                     
print F 'You should have received a copy of the GNU General Public License  ';
print F 'along with this program; if not, write to the Free Software ';
print F 'Foundation, Inc., 59 Temple Place - Suite 330, Boston, ';
print F 'MA  02111-1307, USA.\\\\ \\\\',  "\n\n";
print F '\tableofcontents', "\n\n";
close F;

`../bin/extract_latex < ../dal/dal_std.h >> doc.tex`;
`../bin/extract_latex < ../dal/dal_basic.h >> doc.tex`;
`../bin/extract_latex < ../dal/dal_algobase.h >> doc.tex`;
`../bin/extract_latex < ../bgeot/bgeot_poly.h >> doc.tex`;
`../bin/extract_latex < ../bgeot/bgeot_vector.h >> doc.tex`;
`../bin/extract_latex < ../bgeot/bgeot_convex_structure.h >> doc.tex`;
`../bin/extract_latex < ../bgeot/bgeot_fem_interpolation.h >> doc.tex`;
`../bin/extract_latex < ../bgeot/bgeot_geometric_trans.h >> doc.tex`;
`../bin/extract_latex < ../bgeot/bgeot_poly_integration.h >> doc.tex`;
`../bin/extract_latex < ../bgeot/bgeot_approx_integration.h >> doc.tex`;
`../bin/extract_latex < ../getfem/getfem_config.h >> doc.tex`;
`../bin/extract_latex < ../getfem/getfem_fem.h >> doc.tex`;
`../bin/extract_latex < ../getfem/getfem_mat_elem_type.h >> doc.tex`;
`../bin/extract_latex < ../getfem/getfem_mesh.h >> doc.tex`;
`../bin/extract_latex < ../getfem/getfem_mesh_fem.h >> doc.tex`;

open F, ">>doc.tex" or die;
print F "\n", '\end{document}', "\n";
close F;
