#!/usr/bin/perl

`rm -f doc.tex`;

print `doc++ --tex -o doc1.tex`;

open(F1, "doc1.tex") or die "Open file impossible : $!\n";
open(F2, ">doc.tex") or die "Open file impossible : $!\n";

$li = <F1>;
print F2 "\\documentclass{article}\n";
print F2 "\\oddsidemargin -1.0cm\n";
print F2 "\\evensidemargin -1.0cm\n";
print F2 "\\topmargin -2.2cm\n";
print F2 "\\textheight 24.7cm\n";
print F2 "\\textwidth 18cm\n";
print F2 "\\headheight 1.0cm\n";
while ($li = <F1>) { print F2 $li; }

close(F1);
close(F2);

open F, "latex doc |" or die; print $_ while (<F>); close F;
open F, "latex doc |" or die; print $_ while (<F>); close F;
open F, "dvips -o -p1 doc |" or die; print $_ while (<F>); close F;

`rm -f doc1.tex doc.tex doc.log doc.aux doc.cls` 

