function varargout=get(obj, varargin)
% gfMesherObject/get.m
% see gf_mesher_object_get for more help.
if (nargout), 
  [varargout{1:nargout}] = gf_mesher_object_get(obj, varargin{:});
else
  gf_mesher_object_get(obj,varargin{:});
  if (exist('ans','var') == 1), varargout{1}=ans;
  end;
end;
% autogenerated mfile;
