function a=loadobj(a)
% gfMesherObject/loadobj
% this function is automatically called by matlab when objects of class
% gfMesherObjectare loaded from a MAT-file
  a=gfMesherObject('from string',b.txt);
% autogenerated mfile;
