function varargout=get(obj, varargin)
% gfContStruct/get.m
% see gf_cont_struct_get for more help.
if (nargout), 
  [varargout{1:nargout}] = gf_cont_struct_get(obj, varargin{:});
else
  gf_cont_struct_get(obj,varargin{:});
  if (exist('ans','var') == 1), varargout{1}=ans;
  end;
end;
% autogenerated mfile;
