function a=loadobj(a)
% gfContStruct/loadobj
% this function is automatically called by matlab when objects of class
% gfContStructare loaded from a MAT-file
  a=gfContStruct('from string',b.txt);
% autogenerated mfile;
