function b=saveobj(a)
% gfContStruct/saveobj
% this function is automatically called by matlab when objects of class
% gfContStructare saved in a MAT-file
  b=a; b.txt=char(a);
% autogenerated mfile;
