% FUNCTION [...] = gf_mesh_im_data_get(mesh_im_data MID, [operation [, args]])
%
%   General function extracting information from mesh_im_data objects.
%   
%
%   * gf_mesh_im_data_get(mesh_im_data MID, 'region')
%   Output the region that the mesh_imd is restricted to.
%   
%
%   * gf_mesh_im_data_get(mesh_im_data MID, 'nbpts')
%   Output the number of integration points (filtered in the considered region).
%   
%
%   * gf_mesh_im_data_get(mesh_im_data MID, 'nb tensor elements')
%   Output the size of the stored data (per integration point).
%   
%
%   * gf_mesh_im_data_get(mesh_im_data MID, 'tensor size')
%   Output the dimensions of the stored data (per integration point).
%   
%
%   * gf_mesh_im_data_get(mesh_im_data MID, 'display')
%   displays a short summary for a mesh_imd object.
%
%   * m = gf_mesh_im_data_get(mesh_im_data MID, 'linked mesh')
%   Returns a reference to the mesh object linked to `mim`.
%
%
function [varargout]=gf_mesh_im_data_get(varargin)
  if (nargout),
    [varargout{1:nargout}]=gf_octave('mesh_im_data_get', varargin{:});
  else
    gf_octave('mesh_im_data_get', varargin{:});
    if (exist('ans', 'var') == 1), varargout{1}=ans; end;
  end;
% autogenerated mfile;
