% FUNCTION [...] = gf_mesher_object_get(mesher_object MO, [operation [, args]])
%
%   General function for querying information about mesher_object objects.
%   
%
%   * s = gf_mesher_object_get(mesher_object MO, 'char')
%   Output a (unique) string representation of the mesher_object.
%   
%   This can be used to perform comparisons between two
%   different mesher_object objects.
%   This function is to be completed.
%   
%
%   * gf_mesher_object_get(mesher_object MO, 'display')
%   displays a short summary for a mesher_object object.
%
%
function [varargout]=gf_mesher_object_get(varargin)
  if (nargout),
    [varargout{1:nargout}]=gf_octave('mesher_object_get', varargin{:});
  else
    gf_octave('mesher_object_get', varargin{:});
    if (exist('ans', 'var') == 1), varargout{1}=ans; end;
  end;
% autogenerated mfile;
