function varargout=get(obj, varargin)
% gfMeshImData/get.m
% see gf_mesh_im_data_get for more help.
if (nargout), 
  [varargout{1:nargout}] = gf_mesh_im_data_get(obj, varargin{:});
else
  gf_mesh_im_data_get(obj,varargin{:});
  if (exist('ans','var') == 1), varargout{1}=ans;
  end;
end;
% autogenerated mfile;
