function a=loadobj(a)
% gfMeshImData/loadobj
% this function is automatically called by matlab when objects of class
% gfMeshImDataare loaded from a MAT-file
  a=gfMeshImData('from string',b.txt);
% autogenerated mfile;
