function b=saveobj(a)
% gfMeshImData/saveobj
% this function is automatically called by matlab when objects of class
% gfMeshImDataare saved in a MAT-file
  b=a; b.txt=char(a);
% autogenerated mfile;
