function varargout=get(obj,varargin)
% gfMesh/get.m
% see gf_mesh_get for more help.
if (nargout),
 [varargout{1:nargout}]=gf_mesh_get(obj, varargin{:});
else
 gf_mesh_get(obj,varargin{:});
 if (exist('ans','var') == 1), varargout{1}=ans;
end;
end
% autogenerated by gen_mfiles