function varargout=set(obj,varargin)
% gfMdState/set.m
% see gf_mdstate_set for more help.
if (nargout),
 [varargout{1:nargout}]=gf_mdstate_set(obj, varargin{:});
else
 gf_mdstate_set(obj,varargin{:});
 if (exist('ans','var') == 1), varargout{1}=ans;
end;
end
% autogenerated by gen_mfiles