function a=loadobj(a)
% gfMeshLevelSet/loadobj
% this function is automatically called by matlab when objects of class
% gfMeshLevelSetare loaded from a MAT-file
  a=gfMeshLevelSet('from string',b.txt);
% autogenerated mfile;
