function b=saveobj(a)
% gfMeshLevelSet/saveobj
% this function is automatically called by matlab when objects of class
% gfMeshLevelSetare saved in a MAT-file
  b=a; b.txt=char(a);
% autogenerated mfile;
