function display(gt)
% gfGeoTrans/display displays a short summary for a gfGeoTrans object
% see gfGeoTrans/char for an exhaustive description of the object.

  for i=1:numel(gt),
    disp(sprintf('gfGeoTrans object ID=%2u dim=%d, nbpts=%2d : %s',...
		 double(gt(i).id),...
		 gf_geotrans_get(gt(i),'dim'),...
		 gf_geotrans_get(gt(i),'nbpts'),...
		 gf_geotrans_get(gt(i),'char')));
  end;
