function a=loadobj(a)
% gfModel/loadobj
% this function is automatically called by matlab when objects of class
% gfModelare loaded from a MAT-file
  a=gfModel('from string',b.txt);
% autogenerated mfile;
