function a=loadobj(a)
% gfLevelSet/loadobj
% this function is automatically called by matlab when objects of class
% gfLevelSetare loaded from a MAT-file
  a=gfLevelSet('from string',b.txt);
% autogenerated mfile;
