function display(cs)
% gfGlobalFunction/display displays a short summary for a gfGlobalFunction object 
  for i=1:numel(cs),
    gf_global_function_get(cs(i), 'display');
  end;
% autogenerated mfile;
