function varargout=get(obj, varargin)
% gfGlobalFunction/get.m
% see gf_global_function_get for more help.
if (nargout), 
  [varargout{1:nargout}] = gf_global_function_get(obj, varargin{:});
else
  gf_global_function_get(obj,varargin{:});
  if (exist('ans','var') == 1), varargout{1}=ans;
  end;
end;
% autogenerated mfile;
