function a=loadobj(a)
% gfGlobalFunction/loadobj
% this function is automatically called by matlab when objects of class
% gfGlobalFunctionare loaded from a MAT-file
  a=gfGlobalFunction('from string',b.txt);
% autogenerated mfile;
