function b=saveobj(a)
% gfGlobalFunction/saveobj
% this function is automatically called by matlab when objects of class
% gfGlobalFunctionare saved in a MAT-file
  b=a; b.txt=char(a);
% autogenerated mfile;
