function varargout=get(obj,varargin)
% gfInteg/get.m
% see gf_integ_get for more help.
if (nargout),
 [varargout{1:nargout}]=gf_integ_get(obj, varargin{:});
else
 gf_integ_get(obj,varargin{:});
 if (exist('ans','var') == 1), varargout{1}=ans;
end;
end
% autogenerated by gen_mfiles