function [m,b]=gfCvStruct(a, varargin)
% gfCvStruct class pseudo-constructor
  this_class = 'gfCvStruct';
  if (nargin==0) error('cant create an empty cvstruct reference'); end;
  if (isa(a,this_class)),
    m=a;
  else
    if (isstruct(a) & isfield(a,'id') & isfield(a,'cid'))
      cname = gf_workspace('class name',a);
      if (strcmp(cname, this_class))
	 m = a;
      else
	 m = gf_cvstruct(a,varargin{:});
      end;
    else
      m = gf_cvstruct(a,varargin{:});
    end;
    m.txt = '';
    m = class(m, this_class);
  end;
% autogenerated mfile;
