function a=loadobj(a)
% gfCvStruct/loadobj
% this function is automatically called by matlab when objects of class
% gfCvStructare loaded from a MAT-file
  a=gfCvStruct('from string',b.txt);
% autogenerated mfile;
