name: ci-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  script:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: install
        run: |
          sudo apt update
          sudo apt-get install -y --no-install-recommends automake
          sudo apt-get install -y --no-install-recommends fig2dev
          sudo apt-get install -y --no-install-recommends fig2ps
          sudo apt-get install -y --no-install-recommends g++
          sudo apt-get install -y --no-install-recommends gv
          sudo apt-get install -y --no-install-recommends imagemagick
          sudo apt-get install -y --no-install-recommends liblapack-dev
          sudo apt-get install -y --no-install-recommends libmumps-seq-dev
          sudo apt-get install -y --no-install-recommends libopenblas-dev
          sudo apt-get install -y --no-install-recommends libpython3-dev
          sudo apt-get install -y --no-install-recommends libqd-dev
          sudo apt-get install -y --no-install-recommends libqhull-dev
          sudo apt-get install -y --no-install-recommends libtool
          sudo apt-get install -y --no-install-recommends make
          sudo apt-get install -y --no-install-recommends python3-pip
          sudo apt-get install -y --no-install-recommends python3-venv
          sudo apt-get install -y --no-install-recommends sphinx-intl
          sudo apt-get install -y --no-install-recommends texlive
          sudo apt-get install -y --no-install-recommends xzdec
      - name: update
        env:
          SPHINXINTL_TRANSIFEX_ORGANIZATION_NAME: tkoyama010
          SPHINXINTL_TRANSIFEX_USERNAME: api
          SPHINXINTL_TRANSIFEX_PROJECT_NAME: getfem-doc
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          python3 -m venv /home/runner/work/venv
          source /home/runner/work/venv/bin/activate
          pip3 config set global.index-url https://pypi.python.org/simple/
          pip3 install -U pip setuptools
          pip3 install -r ./requirements.txt
          bash autogen.sh
          ./configure --prefix=/home/runner/work/venv --with-pic
          make -j8 check  >  make.log
