name: ci-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  script:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESSTOKEN }}
      - name: install
        run: |
          sudo apt update
          sudo apt-get install -y --no-install-recommends automake
          sudo apt-get install -y --no-install-recommends fig2dev
          sudo apt-get install -y --no-install-recommends fig2ps
          sudo apt-get install -y --no-install-recommends g++
          sudo apt-get install -y --no-install-recommends gv
          sudo apt-get install -y --no-install-recommends imagemagick
          sudo apt-get install -y --no-install-recommends liblapack-dev
          sudo apt-get install -y --no-install-recommends libmumps-seq-dev
          sudo apt-get install -y --no-install-recommends libopenblas-dev
          sudo apt-get install -y --no-install-recommends libpython3-dev
          sudo apt-get install -y --no-install-recommends libqd-dev
          sudo apt-get install -y --no-install-recommends libqhull-dev
          sudo apt-get install -y --no-install-recommends libtool
          sudo apt-get install -y --no-install-recommends make
          sudo apt-get install -y --no-install-recommends python3-pip
          sudo apt-get install -y --no-install-recommends python3-venv
          sudo apt-get install -y --no-install-recommends sphinx-intl
          sudo apt-get install -y --no-install-recommends texlive
          sudo apt-get install -y --no-install-recommends xzdec
      - name: check
        run: |
          python3 -m venv /home/runner/work/venv
          source /home/runner/work/venv/bin/activate
          pip3 config set global.index-url https://pypi.python.org/simple/
          pip3 install -U pip setuptools
          pip3 install -r ./requirements.txt
          bash autogen.sh
          ./configure --prefix=/home/runner/work/venv --with-pic
          make -j8 install
          make -j8 check
